<a href="https://colab.research.google.com/github/userr2232/numerical-linear-algebra/blob/master/Lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
from numpy.linalg import matrix_rank, inv, det, eigvals
from scipy.linalg import orth, null_space, svdvals

#### Outer Product
* All columns are multiples of $u$ and all rows are multiples of $v$.
* The matrix $uv^T$ has rank 1.

$
uv^T = 
\begin{bmatrix}\phantom{\vert} \\ u \\ \phantom\vert\end{bmatrix}\begin{bmatrix}v_1 & v_2 & v_3 \dots & v_n \end{bmatrix} = 
\left[
    \begin{matrix}
        \phantom\vert \\
        v_1u \\
        \phantom\vert \\
    \end{matrix}
    \left|\
    \begin{matrix}
        \phantom\vert \\
        v_2u \\
        \phantom\vert \\
    \end{matrix}
    \right.
    \left|\
    \begin{matrix}
        \phantom\vert \\
        \dots \\
        \phantom\vert \\
    \end{matrix}
    \right.
    \left|\
    \begin{matrix}
        \phantom\vert \\
        v_nu \\
        \phantom\vert \\
    \end{matrix}
    \right.
\right] =
\begin{bmatrix}
v_1u_1 & \dots & v_nu_1 \\
\vdots & \ddots & \vdots \\
v_1u_m & \dots & v_nu_m
\end{bmatrix}
$

In [55]:
u = np.arange(1,5)[:, np.newaxis]
v = u + 4
u, v

(array([[1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8]]))

In [26]:
u @ v.T

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

#### $B = AR, R$ is a upper-triangular matrix

$b_j = Ar_j = \sum\limits_{k=1}^{j} a_k$

$b_j$ is the sum of the first $j$ columns of A.

In [27]:
A = np.arange(1, 10).reshape(3, 3)
R = np.triu(np.ones(9).reshape(3, 3), k=0)
A, R

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]]))

In [28]:
A @ R

array([[ 1.,  3.,  6.],
       [ 4.,  9., 15.],
       [ 7., 15., 24.]])

### Range and Nullspace

* The range of $A$ is the set of vectors that can be expressed as $Ax$ for a given $x$. In other words, is the space spanned by the columns of $A$ (also known as *column space*).
* The nullspace of $A$, is the set of vectors that when multiplied by $A$ give $0$.

In [64]:
A = np.ones(4).reshape(2, 2)
A

array([[1., 1.],
       [1., 1.]])

In [73]:
range = orth(A)
range # range is the orthonormal basis for the range of A

array([[-0.70710678],
       [-0.70710678]])

In [74]:
ns = null_space(A)
ns # ns is the orthonormal basis for the nullspace of A

array([[-0.70710678],
       [ 0.70710678]])

In [72]:
np.allclose(A @ ns, 0)

True

### Rank

* The column rank is the dimension of the column space.
* rank $=$ row rank $=$ column rank
* A matrix $A \in \mathbb{C}^{m\times n}$ of *full rank* has rank $=$ min(m, n). In other words, it has at least min(m, n) linearly independent columns.
* $A \in \mathbb{C}^{m\times n}$ has *full rank* if and only if it maps no two distinct vectors to the same vector.

In [43]:
I = np.eye(4)
A = I.copy()
A[-1,-1] = 0
matrix_rank(I), matrix_rank(A)

(4, 3)

### Inverse

* A *nonsingular* or *invertible* matrix is a square matrix of full rank.
* Since $A \in \mathbb{C}^{m\times m}$ has full rank, it has $m$ linearly independent columns. 
    * Thus, it forms a basis for the whole space $\mathbb{C}^{m}$. 
        * Therefore, any vector in $\mathbb{C}^{m}$ can be expressed as a linear combination of its columns.
        * In particular, the one-hot vector $e_j$ with 1 in its $j^{th}$ entry, can be expressed as a linear combination of $A$'s columns: $e_j = \sum\limits_{i=1}^{m}z_{ij}a_{i}$

$$
\left[
    \begin{matrix}
        \phantom\vert \\
        e_1 \\
        \phantom\vert \\
    \end{matrix}
    \left|\
    \begin{matrix}
        \phantom\vert \\
        \dots \\
        \phantom\vert \\
    \end{matrix}
    \right.
    \left|\
    \begin{matrix}
        \phantom\vert \\
        e_m \\
        \phantom\vert \\
    \end{matrix}
    \right.
\right] =
I = 
AZ
$$

$Z$ is the *inverse* of A and it's unique. $AA^{-1} = A^{-1}A = I$

The following conditions for $A \in \mathbb{C}^{m\times m}$ are equivalent:

* $A$ has an inverse $A^{-1}$
* $rank(A)$ = m
* $range(A) = \mathbb{C}^{m}$
* $null(A) = {0}$
* $0$ is not an eigenvalue of $A$
* $0$ is not a singular value of $A$
* $det(A) \neq 0$

In [77]:
A = np.arange(1, 5).reshape(2, 2)
I = np.eye(2)

In [78]:
A_1 = inv(A)
np.allclose(A @ A_1, I)

True

In [79]:
matrix_rank(A)

2

In [80]:
orth(A)

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [81]:
null_space(A)

array([], shape=(2, 0), dtype=float64)

In [82]:
eigvals(A)

array([-0.37228132,  5.37228132])

In [83]:
svdvals(A)

array([5.4649857 , 0.36596619])

In [84]:
det(A)

-2.0000000000000004

### Matrix inverse times a vector

$x = A^{-1}b \Leftrightarrow Ax = b$

$x$ is the vector of coefficients of the unique linear expansion of $b$ in the basis of columns of A.

### Exercises

#### 1.1

(a)
$
\begin{bmatrix}
    1 & -1 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & -1 & 1 & 0 \\
    0 & -1 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    1 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0.5 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    b_{11} & b_{12} & b_{13} & b_{14} \\
    b_{21} & b_{22} & b_{23} & b_{24} \\
    b_{31} & b_{32} & b_{33} & b_{34} \\
    b_{41} & b_{42} & b_{43} & b_{44} \\
\end{bmatrix}
\begin{bmatrix}
    2 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    0 & 0 & 0 & 1 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    1 & 0 & 0 & 0 \\
\end{bmatrix}
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & 0 \\
\end{bmatrix}
\begin{bmatrix}
    0 & 0 & 0 \\
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 \\
\end{bmatrix}
$

#### (b)

In [86]:
A = np.matrix([[1, -1, 0, 0], [0, 1, 0, 0], [0, -1, 1, 0], [0, -1, 0, 1]]) @ \
    np.matrix([[1, 0, 1, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) @ \
    np.matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0.5, 0], [0, 0, 0, 1]])
A

matrix([[ 1. , -1. ,  0.5,  0. ],
        [ 0. ,  1. ,  0. ,  0. ],
        [ 0. , -1. ,  0.5,  0. ],
        [ 0. , -1. ,  0. ,  1. ]])

In [87]:
C = np.matrix([[2, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) @ \
    np.matrix([[0, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0]]) @ \
    np.matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 0]]) @ \
    np.matrix([[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]])
C

matrix([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 1],
        [0, 0, 0]])

$
\begin{bmatrix}
    1 & -1 & 0.5 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & -1 & 0.5 & 0 \\
    0 & -1 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    b_{11} & b_{12} & b_{13} & b_{14} \\
    b_{21} & b_{22} & b_{23} & b_{24} \\
    b_{31} & b_{32} & b_{33} & b_{34} \\
    b_{41} & b_{42} & b_{43} & b_{44} \\
\end{bmatrix}
\begin{bmatrix}
    0 & 0 & 0 \\
    1 & 0 & 0 \\
    0 & 1 & 1 \\
    0 & 0 & 0 \\
\end{bmatrix}
$